OrdererOrgs:

  - Domain: example.com
    Name: Orderer
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2


PeerOrgs:

  - Domain: org1.example.com
    EnableNodeOUs: true
    Name: Org1
    Template:
      Count: 3
    Users:
      Count: 1

  - Domain: org2.example.com
    EnableNodeOUs: true
    Name: Org2
    Template:
      Count: 2
    Users:
      Count: 1

  - Domain: org3.example.com
    EnableNodeOUs: true
    Name: Org3
    Template:
      Count: 2
    Users:
      Count: 1
