// Code generated by go-swagger; DO NOT EDIT.

// Package restapi FSS
//
//  Fabric Starter Server
//  Schemes:
//    http
//  Host: localhost:9000
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
