// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Network network
// swagger:model network
type Network struct {

	// orderer
	Orderer *Orderer `json:"orderer,omitempty"`

	// orgs
	Orgs []*Orgs `json:"orgs"`
}

// Validate validates this network
func (m *Network) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrgs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Network) validateOrderer(formats strfmt.Registry) error {

	if swag.IsZero(m.Orderer) { // not required
		return nil
	}

	if m.Orderer != nil {
		if err := m.Orderer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("orderer")
			}
			return err
		}
	}

	return nil
}

func (m *Network) validateOrgs(formats strfmt.Registry) error {

	if swag.IsZero(m.Orgs) { // not required
		return nil
	}

	for i := 0; i < len(m.Orgs); i++ {
		if swag.IsZero(m.Orgs[i]) { // not required
			continue
		}

		if m.Orgs[i] != nil {
			if err := m.Orgs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("orgs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Network) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Network) UnmarshalBinary(b []byte) error {
	var res Network
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
